{{- $configName := include "dt4mob-historical-writer.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configName }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | default "INFO" | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ tpl .Values.config.kafka.bootstrapServers . | quote }}
  KAFKA_SECURITY_PROTOCOL: {{ .Values.config.kafka.securityProtocol | default "SSL" | quote }}
  KAFKA_SSL_CA_LOCATION: "/cluster-ca/ca.crt"
  KAFKA_SSL_CERTIFICATE_LOCATION: "/certs/user.crt"
  KAFKA_SSL_KEY_LOCATION: "/certs/user.key"
  KAFKA_CONSUMER_GROUP: {{ tpl .Values.config.kafka.consumerGroup . | default (printf "%s-historical-writer-group" .Release.Name) | quote }}
  KAFKA_TOPIC: {{ .Values.config.kafka.topic | quote }}
  KAFKA_AUTO_OFFSET_RESET: {{ .Values.config.kafka.autoOffsetReset | quote }}
  TIMESCALE_DATABASE_TIMEZONE: {{ .Values.config.timescaleDatabaseTimezone | default "Europe/Lisbon" | quote }}
