{{- $dbsecretName := .Values.config.dbSecretName | default (printf "%s-timescale-cluster-app" .Release.Name) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dt4mob-historical-writer.fullname" . }}-deployment
  labels:
    {{- include "dt4mob-historical-writer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.config.instances | default 1 }}
  selector:
    matchLabels:
      {{- include "dt4mob-historical-writer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dt4mob-historical-writer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "dt4mob-historical-writer.fullname" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          volumeMounts:
            - name: kafka-creds
              mountPath: /certs
              readOnly: true
            - name: kafka-cluster-ca
              mountPath: /cluster-ca
              readOnly: true
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: TIMESCALE_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: {{ $dbsecretName }}
                  key: uri
          envFrom:
            - configMapRef:
                name: {{ include "dt4mob-historical-writer.fullname" . }}
      volumes:
        - name: kafka-creds
          secret:
            secretName: {{ printf "%s-kafka-cluster-user" .Release.Name }}
        - name: kafka-cluster-ca
          secret:
            secretName: {{ printf "%s-kafka-cluster-cluster-ca-cert" .Release.Name }}
