levelAMSConfig:
  logLevel: "INFO"
  history:
    enabled: false
    baseUrl: "http://127.0.0.1/historic"
    username: null
    password: null
  loader:
    jwt: null
    baseUrl: "http://localhost"
    credentials:
      null
      # username: null
      # password: null
    httpTimeout: 30
    startPageIdx: 1
    instrumentCoordsFile: "instrument_coords.csv"
    parametersChunkSize: 10
    instrumentsChunkSize: 10
  hono:
    secure: false
    host: "127.0.0.1"
    port: null
    device: "device"
    tenant: "tenant"
    password: "changeme"
    topic: "telemetry"
  ditto:
    defaultPolicy: "dt4mob:default"
    username: null
    password: null
    baseUrl: "http://localhost/api/2"

  cafileContents: null

jobs:
  - name: "default"
    cronSchedule: "*/5 * * * *"
    geoAssetId: null
    instrumentIds: []
