levelAMSConfig:
  logLevel: "INFO"
  loader:
    baseUrl: "http://localhost"
    httpTimeout: 30
    startPageIdx: 1
    instrumentCoordsFile: "instrument_coords.csv"
    parametersChunkSize: 10
    instrumentsChunkSize: 10
  hono:
    secure: false
    host: "127.0.0.1"
    port: null
    topic: "telemetry"
  ditto:
    defaultPolicy: "dt4mob:default"
    subject: "test"
    baseUrl: "http://localhost/api/2"

jobs:
  - name: "default"
    cronSchedule: "*/5 * * * *"
    geoAssetId: null
    instrumentIds: []
