{{- include "dt4mob.honoCertificate" ( dict "dot" . "component" "adapter-mqtt" ) }}
---
{{- include "dt4mob.honoCertificate" ( dict "dot" . "component" "adapter-http" ) }}
---
{{- include "dt4mob.honoCertificate" ( dict "dot" . "component" "adapter-amqp" ) }}
