{{- $secretName := printf "%s-garbage-collector-secret" (include "dt4mob.fullname" .) }}


{{- $mqttPassword := "" -}}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
{{- if and $existingSecret $existingSecret.data -}}
  {{- $mqttPassword = index $existingSecret.data "mqtt_password" | b64dec -}}
{{- else -}}
  {{- $mqttPassword = .Values.mqttPassword | default (randAlphaNum 20) -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
stringData:
  ca_cert: "/certs/ca.crt"
  log_level: {{ .Values.garbageCollector.logLevel | quote }}
  mqtt_url: {{ tpl .Values.garbageCollector.mqttUrl . | quote }}
  mqtt_tenant: {{ .Values.tenant | quote }}
  mqtt_device: "garbage_collector"
  mqtt_password: {{ $mqttPassword | quote }}
  mqtt_tls: {{ .Values.garbageCollector.mqttTls | quote }}
  mqtt_publish_topic: "telemetry"
  registry_url: {{ tpl .Values.garbageCollector.registryUrl . | quote }}
  ditto_api_url: {{ tpl .Values.garbageCollector.dittoApiUrl . | quote }}
  ditto_base_api_path: "/api/2"
  ditto_main_auth_username: {{ .Values.garbageCollector.dittoMainAuthUsername | quote }}
