{{- $jobName := printf "%s-garbage-collector-job" (include "dt4mob.fullname" .) }}
{{- $containerName := printf "%s-garbage-collector" (include "dt4mob.fullname" .) }}
{{- $secretName := printf "%s-garbage-collector-secret" (include "dt4mob.fullname" .) }}
{{- $certSecretName := printf "%s-http-adapter-cert" (include "dt4mob.fullname" .) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $jobName }}
spec:
  schedule: {{ .Values.garbageCollector.schedule | quote }}
  concurrencyPolicy: Forbid 
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ $containerName }}
              image: {{ .Values.garbageCollector.image.repository }}:{{ .Values.garbageCollector.image.tag }}
              imagePullPolicy: Always
              volumeMounts:
                - name: adapter-cert
                  mountPath: /certs
                  readOnly: true
              env:
              - name: PYTHONUNBUFFERED
                value: "1"
              envFrom:
                - secretRef:
                    name: {{ $secretName }}
          restartPolicy: OnFailure
          volumes:
            - name: adapter-cert
              secret:
                secretName: {{ $certSecretName }}