apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dt4mob.fullname" . }}-historial-api
  labels:
    {{- include "dt4mob.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ditto.ingress.className }}
  rules:
  - host: {{ .Values.global.host | quote }}
    http:
      paths:
      - path: /historic
        pathType: Prefix
        backend:
          service:
            name: {{ include "dt4mob-historical.fullname" (get .Subcharts "dt4mob-historical") }}-api
            port:
              name: http
