{
 "title": "Cache Metrics",
 "tags": [ "Ditto" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Cache",
    "query": {
     "query": "label_values({__name__=~\"cache_.*\"},cache_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global Hits/Misses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hits/Misses Id and Enforcer Caches",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(cache_hits_total[5m]))",
     "legendFormat": "hits",
     "target": "sumSeries(stats.*.concierge.*.ditto.authorization.*.cache.*.hits.m1_rate)"
    },
    {
     "expr": "sum(idelta(cache_misses_total[5m]))",
     "legendFormat": "misses",
     "target": "sumSeries(stats.*.concierge.*.ditto.authorization.*.cache.*.misses.m1_rate)"
    }
   ]
  },
  {
   "title": "Cache hits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum(idelta(cache_hits_total[5m])) by (cache_name)",
     "legendFormat": "{{cache_name}}"
    }
   ]
  },
  {
   "title": "Cache misses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum(idelta(cache_misses_total[5m])) by (cache_name)",
     "legendFormat": "{{cache_name}}"
    }
   ]
  },
  {
   "title": "Cache evictions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(cache_evictions_total[5m])) by (cache_name)",
     "legendFormat": "{{cache_name}}",
     "target": "sumSeries(stats.*.concierge.*.ditto.authorization.*.cache.*.misses.m1_rate)"
    }
   ]
  },
  { "title": "Cache loading times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "90th percentile load times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(irate(cache_loads_seconds_bucket[5m]) > 0) by (le, cache_name)) or vector(0)",
     "legendFormat": "{{cache_name}}"
    }
   ]
  },
  { "title": "$Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }, "repeat": "Cache" },
  {
   "title": "Hits/Misses ($Cache)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(cache_hits_total{cache_name=~\"$Cache\"}[5m]))",
     "legendFormat": "hits",
     "target": "sumSeries(stats.*.concierge.*.ditto.authorization.enforcer.cache.acl.hits.m1_rate)"
    },
    {
     "expr": "sum(idelta(cache_misses_total{cache_name=~\"$Cache\"}[5m]))",
     "legendFormat": "misses",
     "target": "sumSeries(stats.*.concierge.*.ditto.authorization.enforcer.cache.acl.misses.m1_rate)"
    }
   ]
  },
  {
   "title": "Cache Loader ($Cache)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(cache_loads_success_total{cache_name=~\"$Cache\"}[5m]))",
     "legendFormat": "loads success",
     "target": "sumSeries(stats.*.concierge.*.ditto.authorization.enforcer.cache.acl.loads-success.m1_rate)"
    },
    {
     "expr": "sum(idelta(cache_loads_failure_total{cache_name=~\"$Cache\"}[5m]))",
     "legendFormat": "loads failure",
     "target": "sumSeries(stats.*.concierge.*.ditto.authorization.enforcer.cache.acl.loads-failure.m1_rate)"
    },
    {
     "expr": "sum(idelta(cache_estimated_invalidations_total{cache_name=~\"$Cache\"}[5m]))",
     "legendFormat": "estimated invalidations",
     "target": "sumSeries(stats.*.concierge.*.ditto.authorization.enforcer.cache.acl.estimated-invalidations.m1_rate)"
    },
    {
     "expr": "sum(idelta(cache_evictions_total{cache_name=~\"$Cache\"}[5m]))",
     "legendFormat": "evictions",
     "target": "sumSeries(stats.*.concierge.*.ditto.authorization.enforcer.cache.acl.evictions.m1_rate)"
    }
   ]
  },
  {
   "title": "Cache Size ($Cache)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cache_max_size{cache_name=~\"$Cache\"}",
     "legendFormat": "max ({{instance}})",
     "target": "stats.*.concierge.*.ditto.authorization.enforcer.cache.acl.max-size"
    },
    {
     "expr": "cache_estimated_size{cache_name=~\"$Cache\"}",
     "legendFormat": "estimated ({{instance}})",
     "target": "stats.*.concierge.*.ditto.authorization.enforcer.cache.acl.estimated-size"
    }
   ]
  }
 ]
}