{
 "title": "Connectivity Metrics",
 "tags": [ "Ditto" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": {
     "query": "label_values(message_mapping_seconds_count, instance)"
    }
   },
   {
    "name": "Connection",
    "query": {
     "query": "label_values(message_mapping_seconds_count,ditto_connection_id)"
    }
   },
   {
    "name": "ConnectionType",
    "query": {
     "query": "label_values(message_mapping_seconds_count,ditto_connection_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "open connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(connection_client{instance=~\"$Host\", type=~\"$ConnectionType\", id=~\"$Connection\"}) by (type)",
     "legendFormat": "[{{type}}] Overall"
    }
   ]
  },
  {
   "title": "open connections per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(connection_client{instance=~\"$Host\", type=~\"$ConnectionType\", id=~\"$Connection\"}) by (instance, type)",
     "legendFormat": "[{{type}}] {{instance}}"
    }
   ]
  },
  {
   "title": "active connections over the last 5 minutes",
   "type": "timeseries",
   "description": "Connections which delivered metrics in the last 7 days",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (ditto_connection_type) (count by (instance, ditto_connection_id, ditto_connection_type) (increase(message_mapping_seconds_count{instance=~\"$Host\", ditto_connection_type=~\"$ConnectionType\", ditto_connection_id=~\"$Connection\"}[5m]) > 0))",
     "legendFormat": "[{{ditto_connection_type}}] Overall"
    }
   ]
  },
  {
   "title": "active connections over the last 5 minutes per instance",
   "type": "timeseries",
   "description": "Connections which delivered metrics in the last 7 days",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (instance, ditto_connection_type) (count by (instance, ditto_connection_id, ditto_connection_type) (increase (message_mapping_seconds_count{instance=~\"$Host\", ditto_connection_type=~\"$ConnectionType\", ditto_connection_id=~\"$Connection\"}[5m]) > 0))",
     "legendFormat": "[{{ditto_connection_type}}] {{instance}}"
    }
   ]
  },
  { "title": "Inbound Message rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "#consumed messages per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"consumed\", direction=\"inbound\"}[5m])) by (type) > 0",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"consumed\", direction=\"inbound\"}[5m])) by (type, success) > 0",
     "legendFormat": "{{type}} [success={{success}}]"
    }
   ]
  },
  {
   "title": "#mapped messages per second",
   "type": "timeseries",
   "description": "This number reflects the number of messages that resulted out of payload mappings per second.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"mapped\", direction=\"inbound\"}[5m])) by (type) > 0",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"mapped\", direction=\"inbound\"}[5m])) by (type, success) > 0",
     "legendFormat": "{{type}} [success={{success}}]"
    }
   ]
  },
  {
   "title": "#dropped messages per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"dropped\", direction=\"inbound\"}[5m])) by (type) > 0",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"dropped\", direction=\"inbound\"}[5m])) by (type, success) > 0",
     "legendFormat": "{{type}} [success={{success}}]"
    }
   ]
  },
  {
   "title": "#currently inflight messages waiting for acknowledgements",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(connectivity_ack_handling_counter{instance=~\"$Host\", ditto_connection_id=~\"$Connection\", ditto_connection_type=~\"$ConnectionType\"}) by (ditto_connection_type) > 0",
     "legendFormat": "ditto_connection_type"
    },
    {
     "expr": "sum(connectivity_ack_handling_counter{instance=~\"$Host\", ditto_connection_id=~\"$Connection\", ditto_connection_type=~\"$ConnectionType\"}) by (ditto_connection_type, ditto_connection_id) > 0",
     "legendFormat": "{{ditto_connection_id}} - {{ditto_connection_type}} "
    }
   ]
  },
  {
   "title": "#acknowledged messages per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"acknowledged\", direction=\"inbound\"}[5m])) by (type) > 0",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"acknowledged\", direction=\"inbound\"}[5m])) by (type, success) > 0",
     "legendFormat": "{{type}} [success={{success}}]"
    }
   ]
  },
  {
   "title": "#throttled connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(rate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"throttled\", direction=\"inbound\"}[5m])>0) by (type, id)",
     "legendFormat": "{{type}} - {{id}}"
    }
   ]
  },
  {
   "title": "#enforced messages per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"enforced\", direction=\"inbound\"}[5m])) by (type) > 0",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"enforced\", direction=\"inbound\"}[5m])) by (type, success) > 0",
     "legendFormat": "{{type}} [success={{success}}]"
    }
   ]
  },
  { "title": "Outbound Message rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "#dispatched messages per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"dispatched\", direction=\"outbound\"}[5m])) by (type, id) > 0",
     "legendFormat": "{{type}} {{id}}"
    },
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"dispatched\", direction=\"outbound\"}[5m])) by (type, success) > 0",
     "legendFormat": "{{type}} [success={{success}}]"
    }
   ]
  },
  {
   "title": "#filtered per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"filtered\", direction=\"outbound\"}[5m])) by (type) > 0",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"filtered\", direction=\"outbound\"}[5m])) by (type, success) > 0",
     "legendFormat": "{{type}} [success={{success}}]"
    }
   ]
  },
  {
   "title": "#mapped messages per second",
   "type": "timeseries",
   "description": "This number reflects the number of messages that resulted out of payload mappings per second.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"mapped\", direction=\"outbound\"}[5m])) by (type) > 0",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"mapped\", direction=\"outbound\"}[5m])) by (type, success) > 0",
     "legendFormat": "{{type}} [success={{success}}]"
    }
   ]
  },
  {
   "title": "#dropped messages per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"dropped\", direction=\"outbound\"}[5m])) by (type) > 0",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"dropped\", direction=\"outbound\"}[5m])) by (type, success) > 0",
     "legendFormat": "{{type}} [success={{success}}]"
    }
   ]
  },
  {
   "title": "#published messages per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"published\", direction=\"outbound\"}[5m])) by (type) > 0",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"published\", direction=\"outbound\"}[5m])) by (type, success) > 0",
     "legendFormat": "{{type}} [success={{success}}]"
    }
   ]
  },
  {
   "title": "#acknowledged messages per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"acknowledged\", direction=\"outbound\"}[5m])) by (type) > 0",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(irate(connection_messages_total{instance=~\"$Host\", id=~\"$Connection\", type=~\"$ConnectionType\", category=\"acknowledged\", direction=\"outbound\"}[5m])) by (type, success) > 0",
     "legendFormat": "{{type}} [success={{success}}]"
    }
   ]
  },
  {
   "title": "mapping times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg((idelta(connectivity_message_mapping_seconds_sum{segment=\"overall\", instance=~\"$Host\", ditto_connection_id=~\"$Connection\", ditto_connection_type=~\"$ConnectionType\"}[5m]) / idelta(message_mapping_seconds_count{segment=\"overall\", ditto_connection_id=~\"$Connection\", ditto_connection_type=~\"$ConnectionType\"}[5m])) > 0) by (ditto_mapping_success, direction, ditto_connection_type)",
     "legendFormat": "[{{ditto_connection_type}}] {{direction}} successful: {{ditto_mapping_success}}"
    },
    {
     "expr": "avg((idelta(connectivity_message_mapping_seconds_sum{segment=\"overall\", instance=~\"$Host\", ditto_connection_id=~\"$Connection\", ditto_connection_type=~\"$ConnectionType\"}[5m]) / idelta(message_mapping_seconds_count{segment=\"overall\", ditto_connection_id=~\"$Connection\", ditto_connection_type=~\"$ConnectionType\"}[5m])) > 0) by (ditto_mapping_success, ditto_connection_type)",
     "legendFormat": "[{{ditto_connection_type}}] successful: {{ditto_mapping_success}}"
    },
    {
     "expr": "avg((idelta(connectivity_message_mapping_seconds_sum{segment=\"overall\", instance=~\"$Host\", ditto_connection_id=~\"$Connection\", ditto_connection_type=~\"$ConnectionType\"}[5m]) / idelta(message_mapping_seconds_count{segment=\"overall\", ditto_connection_id=~\"$Connection\", ditto_connection_type=~\"$ConnectionType\"}[5m])) > 0) by (direction, ditto_connection_type)",
     "legendFormat": "[{{ditto_connection_type}}] {{direction}}",
     "target": "alias(sumSeriesWithWildcards(stats.timers.Connectivity.$Host.trace.*_inbound.elapsed-time.mean, 3, 5), 'inbound')"
    },
    {
     "expr": "avg((idelta(connectivity_message_mapping_seconds_sum{segment=\"overall\", instance=~\"$Host\", ditto_connection_id=~\"$Connection\", ditto_connection_type=~\"$ConnectionType\"}[5m]) / idelta(message_mapping_seconds_count{segment=\"overall\", ditto_connection_id=~\"$Connection\", ditto_connection_type=~\"$ConnectionType\"}[5m])) > 0)",
     "legendFormat": "in+outbound"
    }
   ]
  },
  {
   "title": "HTTP push request times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(irate(http_publish_request_time_seconds_bucket{instance=~\"$Host\", id=~\"$Connection\"}[5m]) > 0) by (le)) or vector(0)",
     "legendFormat": "overall"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(http_publish_request_time_seconds_bucket{instance=~\"$Host\", id=~\"$Connection\"}[5m]) > 0) by (le, id))",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}