images:
  api:
    repository: atnog-harbor.av.it.pt/dt4mob/data-lake-api
    tag: latest
    imagePullPolicy: Always
  writer:
    repository: atnog-harbor.av.it.pt/dt4mob/data-gateway
    tag: latest
    imagePullPolicy: Always

kakfaTopic:
  create: true
  name: "exports-test-tenant"
  cluster: "dt4mob-kafka-cluster"

api:
  replicas: 1
  config:
    logLevel: INFO

writer:
  replicas: 1
  config:
    logLevel: INFO
    timescaleDatabaseTimezone: "Europe/Lisbon"
  kafka:
    bootstrapServers: "kafka-cluster-kafka-bootstrap:9092"
    securityProtocol: SSL
    consumerGroup: "consumer-group"
    autoOffsetReset: latest
    # userSecretName: ""
    # trustSecretName: ""

timescale:
  instances: 1

  securityContext:
    postgresUID: 1000
    postgresGID: 1000

  storage:
    storageClass: "local-path"
    size: 10Gi
