FROM python:3.14-slim

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:0.9.27 /uv /uvx /bin/

# Copy the application into the container.
COPY . /app

COPY ./app/static /app/static

# Install the application dependencies.
WORKDIR /app
RUN uv sync --frozen --no-cache

# Run the application.
CMD ["/app/.venv/bin/fastapi", "run", "app/main.py", "--port", "8080", "--host", "0.0.0.0"]