FROM alpine:edge
COPY --from=docker.io/astral/uv:latest /uv /uvx /bin/

RUN apk add --no-cache \
    build-base \
    python3-dev \
    librdkafka-dev \
    python3 && \
    ln -sf python3 /usr/bin/python

WORKDIR /app

COPY . .

RUN mkdir -p /certs

RUN uv sync --locked

CMD ["uv","run","main.py"]