apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dt4mob-data-bridge.name" . }}-config
  labels:
    {{ include "dt4mob-data-bridge.labels" . | nindent 4 }}
data:
  config.toml: |
{{ tpl (dict "hono" .Values.hono "devices" .Values.devices | toToml) $ | indent 4 }}
