apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-job
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: {{ (((.Values.jobs).myBackupJob).concurrencyPolicy) }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: data-bridge
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              volumeMounts:
                - name: config-volume
                  mountPath: /app/config.toml
                  subPath: config.toml
                  readOnly: true
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: {{ .Release.Name }}-config
