{{- $root := .}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dt4mob-historical.fullname" . }}-api
  labels:
    {{- include "dt4mob-historical.api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.config.replicas }}
  selector:
    matchLabels:
      {{- include "dt4mob-historical.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dt4mob-historical.api.labels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: {{ .Values.images.api.repository }}:{{ .Values.images.api.tag }}
          imagePullPolicy: {{ .Values.images.api.imagePullPolicy }}
          ports:
          - name: http
            containerPort: 8080
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: AUTH__CLIENT_ID
              value: {{ .Values.api.config.auth.clientId | quote }}
            - name: AUTH__SERVER_URI
              value: {{ tpl .Values.api.config.auth.serverUri . | quote }}
            - name: AUTH__ISSUER
              {{ $tplIssuers := list }}
              {{- range $i, $issuer := .Values.api.config.auth.issuers }}
              {{- $tplIssuers = append $tplIssuers (tpl $issuer $root) }}
              {{- end }}
              value: {{ $tplIssuers | toJson | quote }}
            - name: AUTH__READ_ROLE
              value: {{ .Values.api.config.auth.readRole | toJson | quote }}
            - name: AUTH__WRITE_ROLE
              value: {{ .Values.api.config.auth.writeRole | toJson | quote }}
            - name: TIMESCALE__CONNECTION
              valueFrom:
                secretKeyRef:
                  name: {{ include "dt4mob-historical.fullname" . }}-cluster-app
                  key: uri
            - name: LOG_LEVEL
              value: {{ .Values.api.config.logLevel | quote }}
            {{- if .Values.api.extraEnv }}
              {{- toYaml .Values.api.extraEnv | nindent 12 }}
            {{- end }}
          {{- with .Values.api.volumeMounts }}
          volumeMounts:
              {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.api.volumes }}
      volumes:
          {{- toYaml . | nindent 8 }}
      {{- end }}
