apiVersion: v1
kind: Service
metadata:
  name: {{ include "dt4mob-historical.fullname" . }}-api-service
spec:
  selector:
    {{- include "dt4mob-historical.api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http 
