apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "dt4mob-historical.fullname" . }}-cluster
spec:
  instances: {{ .Values.timescale.instances }}
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: {{ include "dt4mob-historical.fullname" . }}-timescale
    major: 18
  postgresUID: {{ .Values.timescale.securityContext.postgresUID }}
  postgresGID: {{ .Values.timescale.securityContext.postgresGID }}

  postgresql:
    shared_preload_libraries:
    - 'timescaledb'

  bootstrap:
    initdb:
      postInitApplicationSQL:
       - CREATE EXTENSION IF NOT EXISTS timescaledb;

  storage:
    size: {{ .Values.timescale.storage.size }}
    storageClass: {{ .Values.timescale.storage.storageClass | quote }}
