image:
  repository: "atnog-harbor.av.it.pt/dt4mob/garbage-collector"
  tag: "latest"
  imagePullPolicy: "Always" 

concurrencyPolicy: Forbid
successfulJobsHistoryLimit: 1
failedJobsHistoryLimit: 1

config:
  schedule: "*/5 * * * *"
  logLevel: "INFO"
  ditto:
    apiUrl: "ditto-gateway:8080"
    baseApiPath: "/api/2"
    baseWsPath: "/ws/2"
  auth:
    tokenEndpoint: "https://dt4mob-keycloak:8443/auth/realms/dt4mob/protocol/openid-connect/token"
    # username: ""
    # password: ""
    existingSecret: ""
    caSecret: ""
