image:
  repository: "atnog-harbor.av.it.pt/dt4mob/garbage-collector"
  tag: "v2.0"
config:
  schedule: "*/5 * * * *"
  logLevel: "INFO"
  dittoApiUrl: "{{ .Release.Name }}-ditto-gateway:8080"
  dittoBaseApiPath: "/api/2"
  dittoBaseWsPath: "/ws/2"