image:
  repository: atnog-harbor.av.it.pt/dt4mob/data-gateway
  tag: latest
config:
  instances: 1
  loglevel: INFO
  kafka:
    bootstrapServers: "kafka-cluster-kafka-bootstrap:9092"
    securityProtocol: SSL
    consumerGroup: "consumer-group"
    topic: Exports
    autoOffsetReset: latest
    # userSecretName: ""
    # trustSecretName: ""
# timescaleDatabaseTimezone: ""
