apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: {{ include "dt4mob.fullname" . }}-kafka-cluster
  labels:
    {{- include "dt4mob.labels" . | nindent 4 }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: {{ .Values.kafka.version | quote }}
    metadataVersion: {{ .Values.kafka.metadataVersion | quote }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: true
        authentication:
          type: tls
    config:
      {{- .Values.kafka.config | toYaml | nindent 6 }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
