apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: {{ include "dt4mob.fullname" . }}-controller
  labels:
    strimzi.io/cluster: {{ include "dt4mob.fullname" . }}-kafka-cluster
    {{- include "dt4mob.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.kafka.controller.replicas }}
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        kraftMetadata: shared
        deleteClaim: false

  {{- with .Values.kafka.controller.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  template:
    pod:
      {{- with .Values.kafka.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kafka.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: {{ include "dt4mob.fullname" . }}-broker
  labels:
    strimzi.io/cluster: {{ include "dt4mob.fullname" . }}-kafka-cluster
    {{- include "dt4mob.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.kafka.broker.replicas }}
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        kraftMetadata: shared
        deleteClaim: false

  {{- with .Values.kafka.broker.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  template:
    pod:
      {{- with .Values.kafka.broker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kafka.broker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
