image:
  repository: atnog-harbor.av.it.pt/dt4mob/data-bridge
  # This sets the pull policy for images.
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

schedule: "0 * * * *"


hono:
  http_adapter: "https://<hono-http-adapter>"
  tenant_id: "<hono-tenant-id>"
  server_cert_path: "/path/to/cert.pem"

devices:
  - namespace: "internal"
    policy_id: "meteo:default"
    cert_path: "/path/to/device.crt"
    private_key: "/path/to/device.key"
    strategies:
      - type: "<strategy-type>"
        subject: "<thing-subject>"
      - type: "<strategy-type>"
        subject: "<thing-subject>"
