{
 "title": "Search Performance Metrics",
 "time": { "from": "2025-11-24T15:22:52.090Z", "to": "2025-11-24T15:40:16.485Z" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": {
     "query": "label_values({__name__=~\"things_wildcard_search.*\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "# of Processed Search Requests / second",
   "type": "timeseries",
   "description": "Positive Y axis: stacked search queries\nNegative Y axis: stacked search counts",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(things_wildcard_search_query_seconds_count{instance=~\"$Instance\", segment=\"overall\"}[5m])) by (instance, query_type)",
     "legendFormat": "things search {{query_type}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Search internal roundtrip times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "idelta(things_wildcard_search_query_seconds_sum{instance=~\"$Instance\"}[5m]) / idelta(things_wildcard_search_query_seconds_count{instance=~\"$Instance\"}[5m])",
     "legendFormat": "{{query_type}} - {{segment}} ({{instance}})"
    }
   ]
  },
  {
   "title": "# of search consistency lag measurements",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(things_wildcard_search_updater_consistency_lag_seconds_count{instance=~\"$Instance\", segment=\"overall\", success!=\"true\", success!=\"false\"}[5m]) > 0) by (instance, should_ack)",
     "legendFormat": "timeouts (> 5min) ACK: {{should_ack}} ({{instance}})"
    },
    {
     "expr": "sum(irate(things_wildcard_search_updater_consistency_lag_seconds_count{instance=~\"$Instance\", segment=\"overall\", success=~\"true|false\"}[5m]) > 0) by (instance, should_ack)",
     "legendFormat": "successes ACK: {{should_ack}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Search consistency lag",
   "type": "timeseries",
   "description": "Percentiles are capped to max. 10s",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg((idelta(things_wildcard_search_updater_consistency_lag_seconds_sum{instance=~\"$Instance\"}[5m]) / idelta(things_wildcard_search_updater_consistency_lag_seconds_count{instance=~\"$Instance\", segment=\"overall\", success=\"true\"}[5m])) > 0) by (instance, should_ack)",
     "legendFormat": "average ACK: {{should_ack}} ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(things_wildcard_search_updater_consistency_lag_seconds_bucket{instance=~\"$Instance\", segment=\"overall\", success=\"true\"}[5m])) by (le, instance, should_ack))",
     "legendFormat": "90th percentile ACK: {{should_ack}} ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(things_wildcard_search_updater_consistency_lag_seconds_bucket{instance=~\"$Instance\", segment=\"overall\", success=\"true\"}[5m])) by (le, instance, should_ack))",
     "legendFormat": "median ACK: {{should_ack}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Bulk Update Counts / second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(things_wildcard_search_thing_bulkUpdate_seconds_count{instance=~\"$Instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bulk Update Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "idelta(things_wildcard_search_thing_bulkUpdate_seconds_sum{instance=~\"$Instance\"}[5m]) / idelta(things_wildcard_search_thing_bulkUpdate_seconds_count{instance=~\"$Instance\"}[5m])",
     "legendFormat": "average ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(things_wildcard_search_thing_bulkUpdate_seconds_bucket{instance=~\"$Instance\", segment=\"overall\"}[5m])) by (le, instance))",
     "legendFormat": "90th percentile ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(things_wildcard_search_thing_bulkUpdate_seconds_bucket{instance=~\"$Instance\", segment=\"overall\"}[5m])) by (le, instance))",
     "legendFormat": "median ({{instance}})"
    }
   ]
  },
  {
   "title": "Relative duration per segment (median)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(things_wildcard_search_updater_consistency_lag_seconds_bucket{segment!=\"overall\", should_ack=\"false\"}[5m])) by (le, segment, should_ack))",
     "legendFormat": "{{segment}}"
    }
   ]
  },
  {
   "title": "Updates per Bulk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "idelta(things_wildcard_search_thing_bulkUpdate_updates_per_bulk_sum{instance=~\"$Instance\"}[5m]) / idelta(things_wildcard_search_thing_bulkUpdate_updates_per_bulk_count{instance=~\"$Instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Updater metric (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(wildcard_search_index_update_errors_total[5m]))",
     "legendFormat": "DB Errors"
    },
    {
     "expr": "sum(irate(wildcard_search_full_updates_total[5m]))",
     "legendFormat": "Full updates"
    },
    {
     "expr": "sum(irate(wildcard_search_update_failures_total[5m]))",
     "legendFormat": "Retries"
    },
    {
     "expr": "sum(irate(wildcard_search_patch_updates_total[5m]))",
     "legendFormat": "Patch updates"
    },
    {
     "expr": "sum(irate(wildcard_search_patch_skips_total[5m]))",
     "legendFormat": "Skipped patch updates"
    },
    {
     "expr": "sum(irate(wildcard_search_incorrect_patch_updates_total[5m]))",
     "legendFormat": "Incorrect patch updates"
    }
   ]
  },
  {
   "title": "Background Sync",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(increase(wildcard_search_streamed_snapshots_total[1m]))",
     "legendFormat": "streamed snapshots"
    },
    {
     "expr": "sum(increase(wildcard_search_scanned_index_docs_total[1m]))",
     "legendFormat": "scanned index docs"
    }
   ]
  },
  {
   "title": "MongoDB Search Connection Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"(wildcard_search|wildcard_updater)_pool_.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "MongoDB Search Roundtrips (by MongoClient)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "idelta({__name__=~\"wildcard_search_mongodb_seconds_sum\", instance=~\"$Instance\"}[5m]) / idelta({__name__=~\"wildcard_search_mongodb_seconds_count\", instance=~\"$Instance\"}[5m])",
     "legendFormat": "{{command_name}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Search Roundtrip Comparison - Search Persistence vs. Mongo Client",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\nidelta({__name__=~\"wildcard_search_mongodb_seconds_sum\", instance=~\"$Instance\", command_name=\"find\"}[5m]) \n/ \nidelta({__name__=~\"wildcard_search_mongodb_seconds_count\", instance=~\"$Instance\", command_name=\"find\"}[5m])\n)",
     "legendFormat": "Mongo Client"
    },
    {
     "expr": "avg(\nidelta(things_wildcard_search_query_seconds_sum{segment=\"overall\", instance=~\"$Instance\", query_type=\"query\"}[5m])\n/ \nidelta(things_wildcard_search_query_seconds_count{segment=\"overall\", instance=~\"$Instance\", query_type=\"query\"}[5m])\n)",
     "legendFormat": "Search Persistence"
    }
   ]
  }
 ]
}