{
 "title": "Received-Consumed message metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Messages in queue",
   "type": "stat",
   "description": "The number of messages sitting in the Kafka Queue waiting to be consumed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (tenant) (\r\n  label_replace(\r\n    kafka_consumer_records_lag_max{consumerId=~\".*telemetry.*\"},\r\n    \"tenant\", \"$1\", \"connectionId\", \".*-for-(.*)\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# messages/category (Ditto dt4mob-tenant)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (category, direction, success) (increase(connection_messages_total{id=\"hono-kafka-connection-for-dt4mob\"}[$__range]))",
     "legendFormat": "{{category}}={{success}} ({{direction}})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (tenant) (rate(hono_telemetry_payload_bytes_count{status!=\"forwarded\"}[$__rate_interval]))",
     "legendFormat": "[Hono] {{tenant}}"
    },
    {
     "expr": "sum by (id) (rate(connection_messages_total{direction=\"inbound\", success=\"false\"}[$__rate_interval]))",
     "legendFormat": "[Ditto IN] {{id}}"
    },
    {
     "expr": "sum by (id) (rate(connection_messages_total{direction=\"outbound\", success=\"false\"}[$__rate_interval]))",
     "legendFormat": "[Ditto OUT] {{id}} {{category}}"
    }
   ]
  },
  {
   "title": "# queued messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by (tenant) (\r\n  label_replace(\r\n    kafka_consumer_records_lag_max{consumerId=~\".*telemetry.*\"},\r\n    \"tenant\", \"$1\", \"connectionId\", \".*-for-(.*)\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total messages over period",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (tenant) (increase(hono_telemetry_payload_bytes_count{status=\"forwarded\"}[$__range]))",
     "legendFormat": "[Hono] {{tenant}}"
    },
    {
     "expr": "sum by (tenant) (\r\n  label_replace(\r\n    increase(connection_messages_total{direction=\"inbound\", category=\"mapped\", success=\"true\"}[$__range]),\r\n    \"tenant\", \"$1\", \"id\", \".*-for-(.*)\"\r\n  )\r\n)",
     "legendFormat": "[Ditto] {{tenant}}"
    },
    {
     "expr": "sum by (tenant) (\r\n  label_replace(\r\n    increase(kafka_consumer_records_consumed_total{consumerId=~\".*telemetry.*\"}[$__range]),\r\n    \"tenant\", \"$1\", \"connectionId\", \".*-for-(.*)\"\r\n  )\r\n)",
     "legendFormat": "[Kafka] {{tenant}}"
    }
   ]
  },
  {
   "title": "# messages/sec (Hono)",
   "type": "timeseries",
   "description": "The number of messages per second forwarded by Eclipse Hono",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (tenant) (rate(hono_telemetry_payload_bytes_count{status=\"forwarded\"}[$__rate_interval]))",
     "legendFormat": "[Hono] {{tenant}}"
    },
    {
     "expr": "sum by (tenant) (\r\n  label_replace(\r\n    rate(connection_messages_total{direction=\"inbound\", category=\"mapped\", success=\"true\"}[$__rate_interval]),\r\n    \"tenant\", \"$1\", \"id\", \".*-for-(.*)\"\r\n  )\r\n)",
     "legendFormat": "[Ditto] {{tenant}}"
    },
    {
     "expr": "sum by (tenant) (\r\n  label_replace(\r\n    rate(kafka_consumer_records_consumed_total{consumerId=~\".*telemetry.*\"}[$__rate_interval]),\r\n    \"tenant\", \"$1\", \"connectionId\", \".*-for-(.*)\"\r\n  )\r\n)",
     "legendFormat": "[Kafka] {{tenant}}"
    }
   ]
  }
 ]
}