{
 "title": "General VCI Historic Data Dashboard",
 "time": { "from": "2026-03-24T15:00:00.000Z", "to": "2026-03-26T15:00:00.000Z" },
 "panels": [
  {
   "title": "Vehicle Count per Hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "app",
     "rawSql": "SELECT\n  time_bucket('1 hour', time) AS hour,\n  COUNT(*) AS vehicles\nFROM dittoevent\nWHERE action = 'CREATE'\n  AND thing_id LIKE 'traci:%'\nGROUP BY hour\nORDER BY hour;"
    }
   ]
  },
  {
   "title": "Vehicle Count per Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "targets": [
    {
     "dataset": "app",
     "rawSql": "SELECT\n  time_bucket('1 day', time) AS day,\n  COUNT(*) AS vehicles\nFROM dittoevent\nWHERE action = 'CREATE'\n  AND thing_id LIKE 'traci:%'\nGROUP BY day\nORDER BY day;"
    }
   ]
  },
  {
   "title": "Average speed per Hour (km/h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "app",
     "rawSql": "SELECT\n  time_bucket('1 hour', time) AS hour,\n  AVG((value->'features'->'state'->'properties'->>'speed')::double precision) * 3.6 AS avg_speed\nFROM dittoevent\nWHERE action = 'MERGED'\n  AND thing_id LIKE 'traci:%'\nGROUP BY hour\nORDER BY hour;"
    }
   ]
  },
  {
   "title": "Average speed per Vehicle (km/h)",
   "type": "table",
   "description": "This probably is not right if the same ID can correlate to multiple vehicles.",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 8 },
   "targets": [
    {
     "dataset": "app",
     "rawSql": "SELECT *\nFROM (\n  SELECT\n    thing_id,\n    AVG((value->'features'->'state'->'properties'->>'speed')::double precision) * 3.6 AS avg_speed_per_vehicle\n  FROM dittoevent\n  WHERE action = 'MERGED'\n    AND thing_id LIKE 'traci:%'\n  GROUP BY thing_id\n) t;"
    }
   ]
  }
 ]
}