apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "dt4mob.fullname" . }}-keycloak-cluster
spec:
  instances: {{ .Values.keycloak.db.instances }}

  storage:
    size: {{ .Values.keycloak.db.storage.size }}
    storageClass: {{ .Values.keycloak.db.storage.storageClass }}

  {{- with .Values.keycloak.db.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.keycloak.db.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
