apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dt4mob.fullname" . }}-keycloak-config-service-account
  labels:
    {{- include "dt4mob.keycloak.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dt4mob.fullname" . }}-keycloak-config-role
  labels:
    {{- include "dt4mob.keycloak.labels" . | nindent 4 }}
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  resourceNames: ["{{ include "dt4mob.fullname" . }}-keycloak"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dt4mob.fullname" . }}-keycloak-config-role-binding
  labels:
    {{- include "dt4mob.keycloak.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "dt4mob.fullname" . }}-keycloak-config-service-account
roleRef:
  kind: Role
  name: {{ include "dt4mob.fullname" . }}-keycloak-config-role
  apiGroup: rbac.authorization.k8s.io
