apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "dt4mob.fullname" . }}-keycloak-config
  labels:
    {{- include "dt4mob.keycloak.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  template:
    metadata:
      name: {{ include "dt4mob.fullname" . }}-keycloak-config
      labels:
        {{- include "dt4mob.keycloak.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "dt4mob.fullname" . }}-keycloak-config-service-account
      containers:
      - name: keycloak-config
        image: "{{ .Values.keycloak.config.repository }}:{{ .Values.keycloak.config.tag }}"
        imagePullPolicy: {{ .Values.keycloak.config.pullPolicy }}
        env:
        - name: "KC_CLI_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{ include "dt4mob.fullname" . }}-keycloak-admin
              key: "password"
        - name: "KEYCLOAK_STATEFUL_SET"
          value: "{{ include "dt4mob.fullname" . }}-keycloak"
        - name: "KEYCLOAK_ENDPOINT"
          value: "http://{{ include "dt4mob.fullname" . }}-keycloak:8080/auth"
        - name: "KEYCLOAK_REALM"
          value: "dt4mob"
        - name: "KEYCLOAK_CLIENT"
          value: "ditto"
        - name: "KEYCLOAK_CLIENT_REDIRECTS"
          {{ $tplRedirects := list }}
          {{- range $i, $redirect := .Values.keycloak.config.redirectUris }}
          {{- $tplRedirects = append $tplRedirects (tpl $redirect $) }}
          {{- end }}
          value: {{ $tplRedirects | toJson | quote }}
        - name: "KEYCLOAK_CLIENT_ORIGINS"
          {{ $tplOrigins := list }}
          {{- range $i, $origin := .Values.keycloak.config.clientOrigins }}
          {{- $tplOrigins = append $tplOrigins (tpl $origin $) }}
          {{- end }}
          value: {{ $tplOrigins | toJson | quote }}
        - name: ACCOUNTS_PREFIX
          value: "{{ include "dt4mob.fullname" . }}"
        - name: SECRETS_PREFIX
          value: "{{ include "dt4mob.fullname" . }}"
        - name: SYSTEM_ACCOUNTS
          {{ $systemAccounts := list }}
          {{- if (get .Values "dt4mob-garbage-collector").enabled }}
          {{- $systemAccounts = append $systemAccounts "garbage-collector" }}
          {{- end }}
          {{- if (get .Values "dt4mob-level-ams-loader").enabled }}
          {{- $systemAccounts = append $systemAccounts "level-ams-loader" }}
          {{- end }}
          {{- if (get .Values "dt4mob-meteo-populator").enabled }}
          {{- $systemAccounts = append $systemAccounts "meteo-populator" }}
          {{- end }}
          value: {{ $systemAccounts | join "," | quote }}
