apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "dt4mob.keycloak.labels" . | nindent 4 }}
  name: {{ include "dt4mob.fullname" . }}-keycloak-discovery
spec:
  selector:
	{{- include "dt4mob.keycloak.selectorLabels" . | nindent 4 }}
  clusterIP: None
  type: ClusterIP
