apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "dt4mob.keycloak.labels" . | nindent 4 }}
  name: {{ include "dt4mob.fullname" . }}-keycloak
spec:
  selector:
	{{- include "dt4mob.keycloak.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
      name: http
  type: ClusterIP
