apiVersion: v1
kind: Secret
metadata:
  name: level-ams-loader-config
stringData:
{{- with .Values.levelAMSConfig }}
  config.toml: |
    log_level = {{ .logLevel | quote }}

    {{- with .history}}
    [history]
    enabled = {{ .enabled }}

    base_url = {{ .baseUrl | quote }}

      {{- if and .username .password }}
    username = {{ .username | quote }}
    password = {{ .password | quote }}
      {{- end }}
    {{- end }}

    {{- with .ditto }}
    [ditto]
    default_policy = {{ .defaultPolicy | quote }}
      {{- if and .username .password }}
    username = {{ .username | quote }}
    password = {{ .password | quote }}
      {{- end }}
    base_url = {{ .baseUrl | quote}}
    cafile = "ca.crt"
    {{- end }}

    {{- with .hono }}
    [hono]
    host = {{ .host | quote }}
      {{- if .port }}
    port = {{ .port }}
      {{- end }}

    device = {{ .device | quote }}
    tenant = {{ .tenant | quote }}
    password = {{ .password | quote }}

    secure = {{ .secure }}
    cafile = "ca.crt"

    topic = {{ .topic | quote }}
    {{- end }}

    {{- with .loader }}
    [loader]
    base_url = {{ .baseUrl | quote }}

    http_timeout = {{ .httpTimeout }}
    parameters_chunk_size = {{ .parametersChunkSize }}
    instruments_chunk_size = {{ .instrumentsChunkSize }}
    start_page_idx = {{ .startPageIdx }}
    
    instrument_coords_file = "instrument_coords.csv"

      {{- if .jwt }}
    jwt = {{ .jwt | quote }}
      {{- end }}

      {{- with .credentials }}
    [loader.credentials]
    username = {{ .username | required "loader.credentials.username is required" | quote }}
    password = {{ .password | required "loader.credentials.password is required" | quote }}
      {{- end }}
    {{- end }}
  ca.crt: |
{{ .cafileContents | required "cafileContents is required" | indent 4 }}
  instrument_coords.csv: |
    matricula,x,y,z
    A25.1,-86447.163228000005,-86617.66476,88.951789000000005
    A25.2,-86447.165792999993,-86617.663084999993,91.488307000000006
    A19,-86449.847177999996,-86635.437965000005,89.156358999999995
    A35,-86435.088136999999,-86593.498149999999,89.573831999999996
    I1C,-86435.177771000002,-86593.408488999994,90.374374000000003
    I3C,-86449.940489999994,-86635.410401000001,89.873754000000005
    I2C,-86447.284291999997,-86617.648008999997,92.878058999999993
    I4,-86455.582743000006,-86608.917919,96.825835999999995
    I3 MEEC,-86458.595426,-86619.907198999994,97.076480000000004
{{- end }}
