global:
  host: ""
  tenant: "test-tenant"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

dt4mob-controller:
  config:
    kafka:
      serviceName: "dt4mob-kafka-cluster-kafka-bootstrap"
      tls:
        CASecretName: "dt4mob-kafka-cluster-cluster-ca-cert"
        userSecretName: "dt4mob-application-kafka-user"
    hono:
      deviceRegistryServiceName: "dt4mob-hono-service-device-registry"
      tenant:
        tlsCASecretName: "dt4mob-tenant-ca-secret"
        configMapName: "dt4mob-config"
    ditto:
      gatewayServiceName: "dt4mob-ditto-gateway"
      devopsSecretName: "dt4mob-ditto-gateway-secret"

dt4mob-certificate-service:
  config:
    pathPrefix: "/certificates"
    adminRole: "admin"
    permittedRoles:
      - "certificate-issuer"
    secret:
      name: "{{ .Release.Name }}-tenant-ca-secret"
    oidc:
      issuerURI: "https://{{ .Values.global.host }}/auth/realms/dt4mob"
      clientID: "ditto"

dt4mob-site:
  enabled: true
  repository: "atnog-harbor.av.it.pt/dt4mob/website"
  tag: "latest"
  imagePullPolicy: "Always"
  htpasswdSecretName: "dt4mob-site-htpasswd"
  # resources:
  #   requests:
  #     cpu: 200m

dt4mob-ingress:
  enabled: false
  http:
    serviceName: "dt4mob-hono-adapter-http"
  amqp:
    serviceName: "dt4mob-hono-adapter-amqp"
  mqtt:
    serviceName: "dt4mob-hono-adapter-mqtt"

dt4mob-historical:
  enabled: false
  kafkaTopic:
    create: true
    name: "exports-test-tenant"
    cluster: "dt4mob-kafka-cluster"

  api:
    config:
      auth:
        clientId: "ditto"
        serverUri: "https://{{ .Release.Name }}-keycloak:8443/auth/realms/dt4mob"
        issuers:
        - "https://{{ .Values.global.host }}/auth/realms/dt4mob"
        - "https://{{ .Release.Name }}-keycloak:8443/auth/realms/dt4mob"
        readRole:
        - "historical-read"
        - "admin"
        writeRole:
        - "historical-write"
        - "admin"
    extraEnv:
    - name: REQUESTS_CA_BUNDLE
      value: "/opt/tls/ca.crt"
    volumeMounts:
    - name: internal-keycloak-tls
      mountPath: /opt/tls
      readOnly: true
    volumes:
    - name: internal-keycloak-tls
      secret:
        secretName: dt4mob-internal-keycloak-tls

  writer:
    kafka:
      bootstrapServers: "{{ .Release.Name }}-kafka-cluster-kafka-bootstrap:9092"
      consumerGroup: "{{ .Release.Name }}-historical-writer-group"
      autoOffsetReset: latest
      userSecretName: "{{ .Release.Name }}-historical-kafka-user"
      trustSecretName: "{{ .Release.Name }}-kafka-cluster-cluster-ca-cert"

  timescale:
    instances: 3
    storage:
      storageClass: "local-path"
      size: 10Gi

dt4mob-garbage-collector:
  enabled: false
  config:
    ditto:
      apiUrl: "http://{{ .Release.Name }}-ditto-gateway:8080"
    auth:
      existingSecret: "{{ .Release.Name }}-garbage-collector-credentials"
      caSecret: "{{ .Release.Name }}-internal-keycloak-tls"

dt4mob-level-ams-loader:
  enabled: false

  dittoCredsSecretName: "{{ .Release.Name }}-level-ams-loader-credentials"
  caCertSecretName: "{{ .Release.Name }}-root-ca-secret"

  levelAMSConfig:
    hono:
      secure: true
      host: "{{ .Release.Name }}-hono-adapter-mqtt"
      port: 8883
    ditto:
      subject: "brisa"
      baseUrl: "http://{{ .Release.Name }}-ditto-gateway:8080/api/2"

dt4mob-viz:
  enabled: false

dt4mob-meteo-populator:
  enabled: false
  config:
    ditto:
      url: "http://{{ .Release.Name }}-ditto-gateway:8080/api/2/"
    oidc:
      url: "https://{{ .Release.Name }}-keycloak:8443/auth/realms/dt4mob/protocol/openid-connect/token"
      ca_file: "/run/secrets/keycloak/ca.crt"

  dittoCredentials:
    secret: "{{ .Release.Name }}-meteo-populator-credentials"

  extraVolumeMounts:
  - name: internal-keycloak-tls
    mountPath: /run/secrets/keycloak/ca.crt
    subPath: ca.crt
    readOnly: true
  extraVolumes:
  - name: internal-keycloak-tls
    secret:
      secretName: dt4mob-internal-keycloak-tls

dt4mob-data-bridge:
  enabled: false

  caCertSecretName: "{{ .Release.Name }}-root-ca-secret"

  hono:
    http_adapter: "https://{{ .Release.Name }}-hono-adapter-http:8443"

reloader:
  reloader:
    watchGlobally: false

hono:
  messagingNetworkTypes:
    - kafka

  kafkaMessagingClusterExample:
    enabled: false

  livenessProbeInitialDelaySeconds: 900
  readinessProbeInitialDelaySeconds: 45

  useDynamicNodePorts: true
  useLoadBalancer: false
  externalAccess:
    enabled: false

  otelExporterDisable: true

  deviceRegistryExample:
    type: mongodb
    addExampleData: false

    svc:
      enabled: false

    mongoDBBasedDeviceRegistry:
      containerRegistry: "atnog-harbor.av.it.pt"
      imageName: "capucho/hono-service-device-registry-mongodb"
      imageTag: "2.7.0-SNAPSHOT"

      deployment:
        annotations:
          reloader.stakater.com/auto: "true"

      quarkusLoggingProfile: "prod"

      extraEnv:
      - name: KEY_STORE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: "dt4mob-device-registry-kafka-user"
            key: "user.password"
      - name: MONGODB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: "dt4mob-mongodb-hono-secret"
            key: "password"

      resources:
        requests:
          cpu: 200m
      mongodb:
        connectionString: "mongodb+srv://${hono.mongodb.username}:${hono.mongodb.password}@${hono.mongodb.host}/${hono.mongodb.dbName}?replicaSet=rs0&ssl=false"
        host: "{{ .Release.Name }}-psmdb-db-rs0.{{ .Release.Namespace }}.svc.cluster.local"
        dbName: hono
        username: hono
        password: ${MONGODB_PASSWORD}

    tlsKeysSecret: "dt4mob-device-registry-cert"
    tlsTrustStoreConfigMap: "none"
    tlsTrustStoreSecret:
      secretName: "dt4mob-device-registry-cert"

    extraVolumes:
    - name: kafka-certs
      secret:
        secretName: "dt4mob-device-registry-kafka-user"
    - name: kafka-trust
      secret:
        secretName: "dt4mob-kafka-cluster-cluster-ca-cert"
    extraVolumeMounts:
    - name: kafka-certs
      mountPath: "/opt/hono/tls/kafka-certs"
      readOnly: true
    - name: kafka-trust
      mountPath: "/opt/hono/tls/kafka-trust"
      readOnly: true

  adapters:
    useExternalAuth: true

    # Despite being in the adapters section, it's shared by all services
    kafkaMessagingSpec:
      commonClientConfig:
        bootstrap.servers: "dt4mob-kafka-cluster-kafka-bootstrap:9092"
        security.protocol: "SSL"
        ssl.truststore.type: "PEM"
        ssl.truststore.location: "/opt/hono/tls/kafka-trust/ca.crt"
        ssl.keystore.type: "PKCS12"
        ssl.keystore.password: ${KEY_STORE_PASSWORD}
        ssl.keystore.location: "/opt/hono/tls/kafka-certs/user.p12"

    mqtt:
      resources:
        requests:
          cpu: 200m

      deployment:
        annotations:
          reloader.stakater.com/auto: "true"

      quarkusLoggingProfile: "prod"

      tlsKeysSecret: "dt4mob-adapter-mqtt-cert"
      tlsTrustStoreConfigMap: "none"
      tlsTrustStoreSecret:
        secretName: "dt4mob-adapter-mqtt-cert"

      extraEnv:
      - name: KEY_STORE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: "dt4mob-mqtt-adapter-kafka-user"
            key: "user.password"

      extraVolumes:
      - name: kafka-certs
        secret:
          secretName: "dt4mob-mqtt-adapter-kafka-user"
      - name: kafka-trust
        secret:
          secretName: "dt4mob-kafka-cluster-cluster-ca-cert"
      extraVolumeMounts:
      - name: kafka-certs
        mountPath: "/opt/hono/tls/kafka-certs"
        readOnly: true
      - name: kafka-trust
        mountPath: "/opt/hono/tls/kafka-trust"
        readOnly: true

      hono:
        mqtt:
          bindAddress: "0.0.0.0"
          insecurePortEnabled: false
          keyPath: "/opt/hono/tls/keys/tls.key"
          certPath: "/opt/hono/tls/keys/tls.crt"
        
    http:
      resources:
        requests:
          cpu: 200m

      deployment:
        annotations:
          reloader.stakater.com/auto: "true"

      quarkusLoggingProfile: "prod"

      tlsKeysSecret: "dt4mob-adapter-http-cert"
      tlsTrustStoreConfigMap: "none"
      tlsTrustStoreSecret:
        secretName: "dt4mob-adapter-http-cert"

      extraEnv:
      - name: KEY_STORE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: "dt4mob-http-adapter-kafka-user"
            key: "user.password"

      extraVolumes:
      - name: kafka-certs
        secret:
          secretName: "dt4mob-http-adapter-kafka-user"
      - name: kafka-trust
        secret:
          secretName: "dt4mob-kafka-cluster-cluster-ca-cert"
      extraVolumeMounts:
      - name: kafka-certs
        mountPath: "/opt/hono/tls/kafka-certs"
        readOnly: true
      - name: kafka-trust
        mountPath: "/opt/hono/tls/kafka-trust"
        readOnly: true

      hono:
        http:
          bindAddress: "0.0.0.0"
          insecurePortEnabled: false
          keyPath: "/opt/hono/tls/keys/tls.key"
          certPath: "/opt/hono/tls/keys/tls.crt"

    amqp:
      resources:
        requests:
          cpu: 200m

      deployment:
        annotations:
          reloader.stakater.com/auto: "true"

      quarkusLoggingProfile: "prod"

      tlsKeysSecret: "dt4mob-adapter-amqp-cert"
      tlsTrustStoreConfigMap: "none"
      tlsTrustStoreSecret:
        secretName: "dt4mob-adapter-amqp-cert"

      extraEnv:
      - name: KEY_STORE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: "dt4mob-amqp-adapter-kafka-user"
            key: "user.password"

      extraVolumes:
      - name: kafka-certs
        secret:
          secretName: "dt4mob-amqp-adapter-kafka-user"
      - name: kafka-trust
        secret:
          secretName: "dt4mob-kafka-cluster-cluster-ca-cert"
      extraVolumeMounts:
      - name: kafka-certs
        mountPath: "/opt/hono/tls/kafka-certs"
        readOnly: true
      - name: kafka-trust
        mountPath: "/opt/hono/tls/kafka-trust"
        readOnly: true

      hono:
        amqp:
          bindAddress: "0.0.0.0"
          insecurePortEnabled: false
          keyPath: "/opt/hono/tls/keys/tls.key"
          certPath: "/opt/hono/tls/keys/tls.crt"

  authServer:
    containerRegistry: "atnog-harbor.av.it.pt"
    imageName: "capucho/hono-service-auth"
    imageTag: "2.7.0-SNAPSHOT"

    deployment:
      annotations:
        reloader.stakater.com/auto: "true"

    quarkusLoggingProfile: "prod"

    tlsKeysSecret: "dt4mob-auth-server-cert"
    tlsTrustStoreSecret:
      secretName: "dt4mob-auth-server-cert"

    resources:
      requests:
        cpu: "200m"
        memory: "196Mi"
      limits:
        cpu: "1"
        memory: "256Mi"

    extraVolumes:
      - name: "permissions"
        secret:
          secretName: "dt4mob-permissions"
    extraVolumeMounts:
      - name: "permissions"
        mountPath: "/var/run/hono/auth"
    hono:
      auth:
        svc:
          permissionsPath: "/var/run/hono/auth/permissions.json"
          supportedSaslMechanisms: "EXTERNAL"
          signing:
            # tokenExpiration contains the number of seconds after which tokens issued
            # by the Auth server will expire.
            tokenExpiration: 3600


  commandRouterService:
    containerRegistry: "atnog-harbor.av.it.pt"
    imageName: "capucho/hono-service-command-router-infinispan"
    imageTag: "2.7.0-SNAPSHOT"

    deployment:
      annotations:
        reloader.stakater.com/auto: "true"

    quarkusLoggingProfile: "prod"

    tlsKeysSecret: "dt4mob-command-router-cert"
    tlsTrustStoreConfigMap: "none"
    tlsTrustStoreSecret:
      secretName: "dt4mob-command-router-cert"

    resources:
      limits:
        cpu: "1"
        memory: "800Mi"

    extraEnv:
    - name: KEY_STORE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "dt4mob-command-router-kafka-user"
          key: "user.password"

    extraVolumes:
    - name: kafka-certs
      secret:
        secretName: "dt4mob-command-router-kafka-user"
    - name: kafka-trust
      secret:
        secretName: "dt4mob-kafka-cluster-cluster-ca-cert"
    extraVolumeMounts:
    - name: kafka-certs
      mountPath: "/opt/hono/tls/kafka-certs"
      readOnly: true
    - name: kafka-trust
      mountPath: "/opt/hono/tls/kafka-trust"
      readOnly: true

ditto:
  global:
    jwtOnly: true
    namespacePolicies:
      "*": ["dt4mob.av.it.pt:system-service"]

  connectivity:
    resources:
      cpu: 0.2
      memoryMi: 1024

  gateway:
    resources:
      cpu: 0.2
      memoryMi: 768
    systemProps:
      - "-Dditto.protocol.blocklist.0=raw-request-uri"
      - "-Dditto.protocol.blocklist.1=cache-control"
      - "-Dditto.protocol.blocklist.2=connection"
      - "-Dditto.protocol.blocklist.3=timeout-access"
      - "-Dditto.protocol.blocklist.4=accept-encoding"
      - "-Dditto.protocol.blocklist.5=x-forwarded-scheme"
      - "-Dditto.protocol.blocklist.6=x-forwarded-port"
      - "-Dditto.protocol.blocklist.7=x-forwarded-for"
      - "-Dditto.protocol.blocklist.8=forwarded=for"
      - "-Dditto.protocol.blocklist.9=sec-fetch-mode"
      - "-Dditto.protocol.blocklist.10=sec-fetch-site"
      - "-Dditto.protocol.blocklist.11=accept-language"
      - "-Dditto.protocol.blocklist.12=host"
      - "-Dditto.protocol.blocklist.13=via"
      - "-Dditto.protocol.blocklist.14=sec-ch-ua"
      - "-Dditto.protocol.blocklist.15=sec-ch-ua-mobile"
      - "-Dditto.protocol.blocklist.16=sec-ch-ua-platform"
      - "-Dditto.protocol.blocklist.17=sec-fetch-dest"
      - "-Dditto.protocol.blocklist.18=user-agent"
      - "-Dssl-config.trustManager.stores.0.type=PEM"
      - "-Dssl-config.trustManager.stores.0.path=/opt/ditto/tls/ingress/tls.crt"
      - "-Dssl-config.trustManager.stores.1.type=PEM"
      - "-Dssl-config.trustManager.stores.1.path=/opt/ditto/tls/internal-keycloak/tls.crt"
    config:
      authentication:
        oauth:
          openidConnectIssuers:
            keycloak:
              issuer: ""
              issuers:
              - "dt4mob-keycloak:8443/auth/realms/dt4mob"
              authSubjects:
              - "sub:{{ jwt:sub }}"
              - "user:{{ jwt:preferred_username }}"
              - "role:{{ jwt:resource_access/ditto/roles }}"
              injectClaimsIntoHeaders:
                user_email: "{{ jwt:email }}"
                user_name: "{{ jwt:name }}"
        devops:
          existingSecret: "dt4mob-ditto-gateway-secret"
    extraVolumeMounts:
    - name: ingress-tls
      mountPath: /opt/ditto/tls/ingress
      readOnly: true
    - name: internal-keycloak-tls
      mountPath: /opt/ditto/tls/internal-keycloak
      readOnly: true
    extraVolumes:
    - name: ingress-tls
      secret:
        secretName: dt4mob-ingress-tls
    - name: internal-keycloak-tls
      secret:
        secretName: dt4mob-internal-keycloak-tls

  policies:
    resources:
      cpu: 0.2
      memoryMi: 768

  things:
    resources:
      cpu: 0.2
      memoryMi: 768

  thingsSearch:
    resources:
      cpu: 0.2
      memoryMi: 768

  dittoui:
    resources:
      cpu: 0.05
      memoryMi: 32

  nginx:
    enabled: false

  ingress:
    enabled: true
    className: nginx
    tls:
    - secretName: dt4mob-ingress-tls
    api:
      annotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: "70"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "70"
    ws:
      annotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
    ui:
      annotations:
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      paths:
        - path: /apidoc(/|$)(.*)
          pathType: ImplementationSpecific
          service:
            name: swaggerui
        - path: /ui(/)(.*)
          pathType: ImplementationSpecific
          service:
            name: dittoui

  swaggerui:
    resources:
      memoryMi: 64

  mongodb:
    enabled: false

  dbconfig:
    uriSecret: "dt4mob-mongodb-ditto-secret"

kafka:
  version: 4.3.0
  metadataVersion: 4.3
  controller:
    replicas: 3
    # resources:
    # affinity:
    # tolerations:
  broker:
    replicas: 3
    # resources:
    # affinity:
    # tolerations:
  config:
    offsets.topic.replication.factor: 3
    transaction.state.log.replication.factor: 3
    transaction.state.log.min.isr: 2
    default.replication.factor: 3
    min.insync.replicas: 2
    log.retention.hours: 72 # 3 days
    log.retention.bytes: 2147483648 # 2 GiB
    log.segment.bytes: 157286400 # 150 MiB
    log.retention.check.interval.ms: 300000

psmdb-db:
  image:
    tag: 7.0.24-13
  replsets:
    rs0:
      size: 3
      volumeSpec:
        pvc:
          storageClassName: "local-path"
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 10Gi
  sharding:
    enabled: false
  users:
  - name: ditto
    db: ditto
    passwordSecretRef:
      name: "dt4mob-mongodb-ditto-secret"
      key: "password"
    roles:
    - name: dbOwner
      db: ditto
  - name: hono
    db: hono
    passwordSecretRef:
      name: "dt4mob-mongodb-hono-secret"
      key: "password"
    roles:
    - name: dbOwner
      db: hono
 
keycloak:
  replicas: 1
  db:
    instances: 3
    storage:
      size: "10Gi"
      storageClass: "local-path"
    # resources:
    # affinity:
    # tolerations:
  config:
    repository: "atnog-harbor.av.it.pt/dt4mob/keycloak-config"
    tag: "latest"
    imagePullPolicy: "Always"

    redirectUris:
    - "https://{{ .Values.global.host }}/ui"
    - "https://{{ .Values.global.host }}/viz/login"
    - "https://{{ .Values.global.host }}/viz/login/generic_oauth"

    clientOrigins:
    - "https://{{ .Values.global.host }}"

ingressTLS:
  issuer:
    # Spec of the generated issuer if `existingIssuer` is not defined
    spec:
      selfSigned: {}
    # existingIssuer:
    #   name: ""
    #   kind: Issuer
    #   group: cert-manager.io
  certificate:
    additionalDnsNames: []
    ipAddresses: []

bucketConfig:
  clusterRef:
    name: seaweed
    namespace: seaweedfs
  extraConfig:
    anonymousRead: true
