{{- if or (and (not .Values.config.auth.existingSecret) .Values.config.auth.password) (and (not .Values.config.grafana.existingSecret) .Values.config.grafana.token) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dt4mob-alert-checker.fullname" . }}-secret
  labels:
    {{- include "dt4mob-alert-checker.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and (not .Values.config.auth.existingSecret) .Values.config.auth.password }}
  username: {{ .Values.config.auth.username | quote }}
  password: {{ .Values.config.auth.password | quote }}
  {{- end }}
  {{- if and (not .Values.config.grafana.existingSecret) .Values.config.grafana.token }}
  grafana-token: {{ .Values.config.grafana.token | quote }}
  {{- end }}
{{- end }}
