{{- $secretName := printf "%s-secret" (include "dt4mob-garbage-collector.fullname" .) }}


apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "dt4mob-garbage-collector.labels" . | nindent 4 }}
type: Opaque
stringData:
  log_level: {{ .Values.config.logLevel | quote }}
  ditto_api_url: {{ tpl .Values.config.dittoApiUrl . | quote }}
  ditto_base_api_path: {{ .Values.config.dittoBaseApiPath}}
  ditto_base_ws_path: {{ .Values.config.dittoBaseWsPath}}
  ditto_username: {{ .Values.config.dittoUsername | quote }}
  ditto_password: {{ .Values.config.dittoPassword | quote }}
