{{- if and (not .Values.config.existingSecret) .Values.config.dittoPassword -}}
{{- $secretName := printf "%s-secret" (include "dt4mob-garbage-collector.fullname" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "dt4mob-garbage-collector.labels" . | nindent 4 }}
type: Opaque
stringData:
  ditto_username: {{ .Values.config.dittoUsername | quote }}
  ditto_password: {{ .Values.config.dittoPassword | quote }}
{{- end }}